apiVersion: v1
kind: Service
metadata:
  name: secure-bank-service
spec:
  type: NodePort       # Exposes the service outside the internal cluster
  selector:
    app: secure-bank   # Connects to your running pod
  ports:
    - protocol: TCP
      port: 80         # The port we want to use
      targetPort: 5000 # The port your Flask app is listening on